### ISSUE TITLE
Error: invalid address - when calling the "issue" function

### ISSUE THREAD

**Issue by tpmccallum** [bancorprotocol/contracts#241]
After deploying the SmartToken contract on an Ethereum test network I am unable to call the issue function. I get the following error.

Error: invalid address
    at web3-cmt.js:12250:13
    at web3-cmt.js:12080:18
    at web3-cmt.js:13332:28
    at map (<native code>)
    at web3-cmt.js:13331:12
    at web3-cmt.js:13357:18
    at web3-cmt.js:13382:23
    at web3-cmt.js:12448:16
    at apply (<native code>)
    at web3-cmt.js:12534:16

I have tried all of these addresses, they should be valid, not sure what is going on.
"0xfc4067602f68b3b729000ef92cff05f2b94aa5fb", "0xdc13d113fca85a2873d9ffd254bc556d80e52483", "0xab52776885fb487ab60fd10f77604cb5dda4f6f5"

I can call other functions
> contractInstance.totalSupply()
0

**Comment by tpmccallum** [comment]
@barakman showed me that you can use the {from:} as part of the function call.
This is no longer an issue.
Thank you @barakman 👍
deployedContract.issue("0xf7fca0066bde97e5509591afc9f669991e03c25c",10000000000, {from:accountA});
