### ISSUE TITLE
One of the unit tests failed - 1) verifies prioritized quick buy with trusted signature

### ISSUE THREAD

**Issue by tpmccallum** [bancorprotocol/contracts#244]
1) verifies prioritized quick buy with trusted signature

```
... 
    ✓ should throw when attempts to call multiple convertFor with wrong path index (82ms)
    ✓ should throw when attempts to call multiple convertFor with zero amount in the amounts array
    1) verifies prioritized quick buy with trusted signature
    > No events were emitted
    ✓ should throw when attempts to call quick convert prioritized with untrusted signature (200ms)
...
```

```
2865 passing (5m)
  1 failing

  1) Contract: BancorNetwork
       verifies prioritized quick buy with trusted signature:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1085:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)


```
I used the following procedure to perform the unit tests
https://github.com/CyberMiles/tim-research/blob/master/bancor/unit_testing/bancor_unit_testing.asciidoc

Kind regards
Tim

**Comment by barakman** [comment]
@tpmccallum:

All tests pass with:
- web3 client: truffle v4.1.14
- eth node: ganache-cli v6.1.8

What is your system configuration?

**Comment by tpmccallum** [comment]
Hi @barakman 
I am using 
```
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
Ganache CLI v6.1.0 (ganache-core: 2.1.0)
node  v10.9.0
npm v6.2.0
```
I know what you mean about the timing-related issue. I really like the way that you use await :-) very well done.

So I ran the tests again. This is the code for the test in question. It is from contracts/solidity/test/BancorNetwork.js

```
it('verifies prioritized quick buy with trusted signature', async () => {
        await converter1.setQuickBuyPath(smartToken1QuickBuyPath);
        let prevBalance = await smartToken1.balanceOf.call(accounts[1]);

        let block = await web3.eth.blockNumber;
        let maximumBlock = block + 100;
        let gasPrice = defaultGasPriceLimit;

        let soliditySha3 = web3Utils.soliditySha3(maximumBlock, gasPrice, accounts[1], converter1.address, 100, {'type': 'address', 'value': smartToken1QuickBuyPath});
        let result = sign(soliditySha3, accountPrivateKey);

        await converter1.quickConvertPrioritized(smartToken1QuickBuyPath, 100, 1, maximumBlock, result.v, result.r, result.s, { from: accounts[1], value: 100 });
        let newBalance = await smartToken1.balanceOf.call(accounts[1]);
        assert.isAbove(newBalance.toNumber(), prevBalance.toNumber(), "new balance isn't higher than previous balance");
    });
````

I am still getting the following output to the npm test

```
1) verifies prioritized quick buy with trusted signature
    > No events were emitted

  2865 passing (4m)
  1 failing

  1) Contract: BancorNetwork
       verifies prioritized quick buy with trusted signature:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1085:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```
Kind regards
Tim

**Comment by barakman** [comment]
@tpmccallum:
This happens possibly because the value of the `gasPrice` parameter in your Truffle configuration file (`truffle.js` or `truffle-config.js`) is smaller than the value of the `defaultGasPriceLimit` variable in the BancorNetwork test file (`BancorNetwork.js`).

Can you please check these two files and tell us whether or not this is indeed the case?

One way to fix it without dependency, is to replace the hard-coded initialization of `defaultGasPriceLimit` with this:

    let defaultGasPriceLimit = BancorGasPriceLimit.class_defaults.gasPrice;

It's kind of a hacky method, so I will look for alternatives.

Can you please check the above?

Thanks

**Comment by tpmccallum** [comment]
Hi,
Agreed, thank you. I can confirm, as you say, that my defaultGasPriceLimit in the BancorNetwork.js and the gasPrice in the truffle-config.js are the same i.e. 20000000000

I will use branch 0.4.4 as you suggested.

Thank you
